FROM ubuntu:jammy
LABEL org.opencontainers.image.authors="Apache ORC project <dev@orc.apache.org>"
LABEL org.opencontainers.image.licenses="Apache-2.0"
LABEL org.opencontainers.image.ref.name="Apache ORC on Ubuntu 24"
LABEL org.opencontainers.image.version=""
